## Day 30 Lecture 1 Assignment

In this assignment, we will learn about random forests. We will use the mushrooms dataset loaded below.

In [0]:
%matplotlib inline

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [0]:
mushrooms = pd.read_csv('https://tf-assets-prod.s3.amazonaws.com/tf-curric/data-science/mushrooms.csv')

In [4]:
mushrooms.head()

class cap-shape cap-surface  ... spore-print-color population habitat
0     p         x           s  ...                 k          s       u
1     e         x           s  ...                 n          n       g
2     e         b           s  ...                 n          n       m
3     p         x           y  ...                 k          s       u
4     e         x           s  ...                 n          a       g

[5 rows x 23 columns]

After examining the data, we will look for missing values and drop the rows that contain any missing values.

In [11]:
# answer below:
mushrooms.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
class                       8124 non-null object
cap-shape                   8124 non-null object
cap-surface                 8124 non-null object
cap-color                   8124 non-null object
bruises                     8124 non-null object
odor                        8124 non-null object
gill-attachment             8124 non-null object
gill-spacing                8124 non-null object
gill-size                   8124 non-null object
gill-color                  8124 non-null object
stalk-shape                 8124 non-null object
stalk-root                  8124 non-null object
stalk-surface-above-ring    8124 non-null object
stalk-surface-below-ring    8124 non-null object
stalk-color-above-ring      8124 non-null object
stalk-color-below-ring      8124 non-null object
veil-type                   8124 non-null object
veil-color                  8124 non-null object
ring-number

In this dataset, we would like to predict the class (p for poisonous and e for edible). We observe that all columns contain characters. Therefore, we will create dummy variables out of all columns. In the cell below, create dummy variables for every column in the dataset. Remember to drop the first value in each feature.

In [10]:
#answer below:
dummies = pd.get_dummies(mushrooms, drop_first=True)
dummies.head()


class_p  cap-shape_c  cap-shape_f  ...  habitat_p  habitat_u  habitat_w
0        1            0            0  ...          0          1          0
1        0            0            0  ...          0          0          0
2        0            0            0  ...          0          0          0
3        1            0            0  ...          0          1          0
4        0            0            0  ...          0          0          0

[5 rows x 96 columns]

Next, split the data into test and train. Place 20% of the data in the test subset. Recall that class_p is now our y variable.

In [0]:
# answer below:
from sklearn.model_selection import  train_test_split


X=dummies.drop('class_p', axis=1)
y=dummies['class_p']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.9)





We will generate a random forest model from our mushroom data. Below you will initialize the random forest classifier and fit the model.

In [55]:
# answer below:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

rfc = RandomForestClassifier(n_jobs = -1)

results = rfc.fit(X_train, y_train)



/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [56]:
rf_score = rfc.score(X_test, y_test)
rf_predictions = rfc.predict(X_test)

print(rf_score, '\n',rf_predictions)

0.99972647702407 
 [1 0 1 ... 1 0 1]


To evaluate our model, produce the predicted values for the test sample.

In [57]:
# answer below:
from sklearn.model_selection import cross_val_score

cross_val_score(rfc, X_train, y_train, cv=5)

array([0.99390244, 0.99382716, 1.        , 0.98765432, 1.        ])

Next, we will print the confusion matrix. Explain our results.

In [58]:
# answer below:
from sklearn.metrics import confusion_matrix

confusion = confusion_matrix(y_test, rf_predictions, labels = [1,0])

print(confusion)

[[3503    2]
 [   0 3807]]


Print the feature importances ordered by importance. Explain your results:

In [78]:
# answer below:
df_importance=pd.DataFrame({'feature': X_train.columns, 'importance': rfc.feature_importances_}).sort_values(by='importance', ascending=False)

df_importance.head(50)

feature  importance
22                      odor_n    0.117776
19                      odor_f    0.085960
28                 gill-size_n    0.065612
43                stalk-root_e    0.061431
17                   bruises_t    0.058971
45  stalk-surface-above-ring_k    0.057724
76         spore-print-color_h    0.050218
78         spore-print-color_n    0.045462
75                 ring-type_p    0.040512
46  stalk-surface-above-ring_s    0.033694
87                population_v    0.031320
77         spore-print-color_k    0.024453
49  stalk-surface-below-ring_s    0.022767
6                cap-surface_s    0.021701
27              gill-spacing_w    0.019971
41                stalk-root_b    0.018433
82         spore-print-color_w    0.018150
18                      odor_c    0.016787
71               ring-number_t    0.014502
89                   habitat_g    0.014112
33                gill-color_n    0.012858
40               stalk-shape_t    0.012560
57    stalk-color-above-ring_w    0.011682
20                      odor_l    0.010429
23                      odor_p    0.010046
15                 cap-color_w    0.009133
93                   habitat_u    0.007109
7                cap-surface_y    0.006979
48  stalk-surface-below-ring_k    0.006811
2                  cap-shape_k    0.006238
86                population_s    0.006153
55    stalk-color-above-ring_o    0.005887
80         spore-print-color_r    0.005304
50  stalk-surface-below-ring_y    0.004524
24                      odor_s    0.004251
4                  cap-shape_x    0.004167
88                population_y    0.004131
10                 cap-color_g    0.003606
42                stalk-root_c    0.003550
63    stalk-color-below-ring_o    0.003376
9                  cap-color_e    0.003224
26           gill-attachment_f    0.003178
16                 cap-color_y    0.002819
65    stalk-color-below-ring_w    0.002623
58    stalk-color-above-ring_y    0.002590
11                 cap-color_n    0.002272
60    stalk-color-below-ring_e    0.002207
1                  cap-shape_f    0.002147
39                gill-color_y    0.002139
70               ring-number_o    0.001797

In [72]:
type(df_importance)

pandas.core.frame.DataFrame

In [62]:
 !cat /proc/cpuinfo

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 63
model name	: Intel(R) Xeon(R) CPU @ 2.30GHz
stepping	: 0
microcode	: 0x1
cpu MHz		: 2300.000
cache size	: 46080 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs
bogomips	: 4600.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: